// <auto-generated />
namespace BJN.Services.Connectors.Lti.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addltimeeting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addltimeeting));
        
        string IMigrationMetadata.Id
        {
            get { return "201601032202538_add-ltimeeting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
