// <auto-generated />
namespace BJN.Services.Connectors.Lti.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduseremailtoltiMeeting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduseremailtoltiMeeting));
        
        string IMigrationMetadata.Id
        {
            get { return "201601180348306_add-user-email-to-ltiMeeting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
